# NumPy Practice Notebook

This notebook contains a series of practice problems to help you understand and apply core concepts in NumPy.

---

## 🧩 1. Array Creation
**Question:** Create the following arrays using NumPy:
1. A 1D array with numbers from 0 to 9
2. A 2D array of shape (3, 3) filled with zeros
3. A 2D array of shape (2, 4) filled with ones
4. A 3x3 identity matrix


---


In [6]:
import numpy as np
# 1D Array
arr_1d=np.arange(10)
print(arr_1d)
# 2D Array
arr_2d=np.zeros((3,3))
print(arr_2d)
# 3D Array
arr_3d=np.ones((2,4))
print(arr_3d)
# 3x3 Identity Matrix
arr_identity=np.eye(3)
print(arr_identity)


[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## 🧪 2. Array Inspection
**Question:** Given a NumPy array `arr`, print:
1. Its shape
2. Its data type
3. The number of dimensions
4. The total number of elements

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```

---


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# The shape of the array
print(arr.shape)
# The data type of array elements
print(arr.dtype) 
# The number of dimensions of the array
print(arr.ndim)
# the total number of elements in the array
print(arr.size)

(2, 3)
int64
2
6



## 🔍 3. Indexing and Slicing
**Question:** Using the array below, do the following:
1. Slice the first two rows
2. Get the last column
3. Extract the element in the second row and third column
4. Reverse the rows

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

```


In [26]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
# Slicing the first two rows
print('The first two rows:\n',arr[0:2,0:])
# The last column
print('The last column:\n',arr[:,-1])
# The element in the second row and third column
print('The element in the second row and third column:',arr[1,2])
# The reverse of rows
print('The reverse of rows:\n',arr[::-1,:])

The first two rows:
 [[10 20 30]
 [40 50 60]]
The last column:
 [30 60 90]
The element in the second row and third column: 60
The reverse of rows:
 [[70 80 90]
 [40 50 60]
 [10 20 30]]



---

## 🔁 4. More Slicing Practice
**Question:**
Given the array below, extract:
1. All even numbers
2. The second and third rows
3. The last two columns
4. A subarray containing the middle 2x2 block

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

```


In [36]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
# All even numbers
evens=arr[arr%2==0]
print('All even numbers:', evens)
# The second and third rows
print('The second and third rows:\n',arr[1:3,:])
# The last two columns
print('The last two columns:\n',arr[:,2:4])
# The middle 2x2 block
print('The middle 2x2 block:\n',arr[1:3,1:3])

All even numbers: [ 2  4  6  8 10 12 14 16]
The second and third rows:
 [[ 5  6  7  8]
 [ 9 10 11 12]]
The last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
The middle 2x2 block:
 [[ 6  7]
 [10 11]]



---

## ➕ 5. Arithmetic Operations
**Question:** Perform the following using NumPy arrays:
1. Add two arrays element-wise
2. Multiply two arrays element-wise
3. Raise all elements of an array to the power of 2

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

```

---


In [40]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Element-wise addition
arr_sum=arr1+arr2
print('Element-wise addition:', arr_sum)
# Element-wise multiplication
arr_multiply=arr1*arr2
print('Element-wise multiplication:', arr_multiply)
# elements of arr1 raised to power 2
arr_power=arr1**2
print('Elements of arr1 raised to power 2:', arr_power)

Element-wise addition: [5 7 9]
Element-wise multiplication: [ 4 10 18]
Elements of arr1 raised to power 2: [1 4 9]



## 📏 6. Broadcasting
**Question:** Use broadcasting to:
1. Add a 1D array to each row of a 2D array
2. Multiply each row of a 2D array by a 1D array
3. Subtract a scalar from each element in an array
4. Add a column vector to each column of a matrix

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

```


In [49]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
C = np.array([[1],
              [2]])

# Broadcasting Adding a 1D array to a 2D array
result_1=A+B
print('Broadcasting Adding a 1D array to a 2D array:\n', result_1)
# Broadcasting Multiply each row of a 2D array by a 1D array
result_2=A*B
print('Broadcasting Multiply each row of a 2D array by a 1D array:\n', result_2) 
# Broadcasting Subtract a scalar from each element in an array
result_3=A-1
print('Broadcasting Subtract a scalar from each element in an array:\n', result_3)
# Broadcasting Add a column vector to each column of a matrix
result_4=A+C
print('Broadcasting Add a column vector to each column of a matrix:\n', result_4)


Broadcasting Adding a 1D array to a 2D array:
 [[11 22 33]
 [14 25 36]]
Broadcasting Multiply each row of a 2D array by a 1D array:
 [[ 10  40  90]
 [ 40 100 180]]
Broadcasting Subtract a scalar from each element in an array:
 [[0 1 2]
 [3 4 5]]
Broadcasting Add a column vector to each column of a matrix:
 [[2 3 4]
 [6 7 8]]



---

## 🔁 7. More Broadcasting Practice
**Question:** Try these:
1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
2. Multiply a (3,1) column array to a (1,4) row array and observe the shape
3. Add a scalar to the entire array

```python
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

```


In [67]:
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2],
              [3],
              [4]])
D=np.arange(4).reshape(1,4)
print(A)
print(D)
# Broadcasting Addind a 1D array of shape (4,) to a 2D array of shape (3,4)
result_5=A+B
print('Broadcasting Addind a 1D array of shape (4,) to a 2D array of shape (3,4):\n', result_5)
# Broadcasting Multiply a (3,1) column array to a (1,4) row array
result_6=C*D
print('Broadcasting Multiply a (3,1) column array to a (1,4) row array and observe the shape:\n', result_6,'\n', result_6.shape)
# Adding a scalar to the entire array
result_7=A+10
print('Adding a scalar to the entire array:\n', result_7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
Broadcasting Addind a 1D array of shape (4,) to a 2D array of shape (3,4):
 [[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]
Broadcasting Multiply a (3,1) column array to a (1,4) row array and observe the shape:
 [[ 0  2  4  6]
 [ 0  3  6  9]
 [ 0  4  8 12]] 
 (3, 4)
Adding a scalar to the entire array:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]



---

## 🔃 8. Reshaping and Flattening
**Question:**
1. Reshape a 1D array of 12 elements into a 3x4 matrix
2. Flatten a 2D array into a 1D array

```python
arr = np.arange(12)

```


In [73]:
arr = np.arange(12)
print(arr)
print(arr.shape)
# Reshape a 1D array of 12 elements into a 3x4 matrix
arr_reshaped=arr.reshape(3,4)
print('Reshaped array:\n', arr_reshaped)
# Flatten a 2D array into a 1D array
arr_1d=arr_reshaped.flatten()
print('Flattened array:\n',arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]



---

## 🔗 9. Stacking and Splitting
**Question:** Stack and split arrays:
1. Stack two (2, 2) arrays vertically and horizontally
2. reshape a (4, 4) array into array of shape (2, 8)


---


In [76]:
arr1=np.zeros((2,2))
arr2=np.ones((2,2))
# Stack two (2, 2) arrays vertically
vertical_arr=np.vstack((arr1,arr2))
print('Vertical array:\n',vertical_arr)
# Stack two (2, 2) arrays horizontally
horizontal_arr=np.hstack((arr1,arr2))
print('horizontal array:\n',horizontal_arr)



Vertical array:
 [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]
horizontal array:
 [[0. 0. 1. 1.]
 [0. 0. 1. 1.]]



## 🧠 10. Boolean Masking
**Question:**
Given an array:
1. Select all elements > 10
2. Replace all even numbers with -1

```python
arr = np.array([[5, 10, 15], [20, 25, 30]])

```


In [79]:
arr = np.array([[5, 10, 15], [20, 25, 30]])
# Selecting all elements > 10
great_than_10=arr[arr>10]
print('All elements greater than 10:',great_than_10)
# Replacing all even numbers with -1
arr[arr%2==0]=-1
print('Array after replacig even numbers with -1:\n',arr)

All elements greater than 10: [15 20 25 30]
Array after replacig even numbers with -1:
 [[ 5 -1 15]
 [-1 25 -1]]



---

## 🧮 11. Aggregation
**Question:** Calculate:
1. Sum of all elements
2. Mean of each column
3. Max value in each row
4. Standard deviation of the array

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```


In [84]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Sum of all elements
res_1=arr.sum()
print('Sum of all elements =',res_1)
# Mean of each column
res_2=np.mean(arr,axis=0)
print('Mean of each column:',res_2)
# Max value in each row
res_3=np.max(arr,axis=1)
print('Max value in each row:',res_3)
# Standard deviation of the array
res_4=np.std(arr)
print('Standard deviation of the array =',res_4)

Sum of all elements = 21
Mean of each column: [2.5 3.5 4.5]
Max value in each row: [3 6]
Standard deviation of the array = 1.707825127659933



---

## 🧲 12. Dot Product and Matrix Multiplication
**Question:**
1. Multiply two matrices using `np.dot`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

```


In [86]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
product=np.dot(A,B)
print('The dot product of two arrays:\n',product)

The dot product of two arrays:
 [[19 22]
 [43 50]]



---

## 🔢 13. Random Numbers
**Question:**
1. Generate a 2x3 array of random numbers between 0 and 1
2. Generate 10 random integers between 50 and 100



In [91]:
# 2x3 array of random numbers between 0 and 1
arr1=np.random.rand(2,3)
print('Array of random numbers:\n',arr1)
# 10 random integers between 50 and 100
random_integers=np.random.randint(50,101,size=10)
print('10 random integers between 50 and 100:\n',random_integers)

Array of random numbers:
 [[0.95759059 0.54270656 0.60696179]
 [0.26951364 0.12674622 0.8594665 ]]
10 random integers between 50 and 100:
 [100  85  82  54  95  71  84  82  97  92]



---

## 📐 14. Linear Algebra
**Question:**
1. Find the rank of a matrix
2. Compute the inverse of a matrix
3. Compute the determinant of a matrix



---


In [98]:
arr=np.array([[1,2],
              [4,5]])
# The rank of a matrix
matrix_rank=np.linalg.matrix_rank(arr)
print('The rank of matrix =',matrix_rank)
# The inverse of matrix
matrix_inverse=np.linalg.inv(arr)
print('The inverse of matrix:\n',matrix_inverse)
# The determinant of a matrix
matrix_determinant=np.linalg.det(arr)
print('The determinant of a matrix =',matrix_determinant)


The rank of matrix = 2
The inverse of matrix:
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
The determinant of a matrix = -2.9999999999999996



## ⭐ Bonus Challenge
**Question:**
Given a 2D array of shape (6, 6), extract all 3x3 submatrices (using slicing) and store them in a list.



In [110]:
list=[]
arr=np.arange(36).reshape(6,6)
# First 3x3 submatrices
first=arr[0:3,0:3]
# Second 3x3 submatrices
second=arr[0:3,3:6]
# Third 3x3 submatrices
third=arr[3:6,0:3]
# Fourth 3x3 submatrices
fourth=arr[3:6,3:6]
list.append(first)
list.append(second)
list.append(third)
list.append(fourth)
list


[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]),
 array([[21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]


---

Happy coding! 🎯
